astrology_domains_charts = {
    "Overall Life": ["Rasi", "Navamsa"],
    "Personality": ["Rasi"],
    "Health": ["Rasi", "Shasthamsa"],
    "Wealth": ["Rasi", "Hora"],
    "Career": ["Rasi", "Dasamsa"],
    "Relationships": ["Rasi", "Navamsa"],
    "Family": ["Rasi"],
    "Education": ["Rasi", "Siddhamsa"],
    "Marriage": ["Navamsa"],
    "Spouse": ["Navamsa"],
    "Spirituality": ["Navamsa", "Vimsamsa"],
    "Financial Status": ["Hora"],
    "Prosperity": ["Hora"],
    "Siblings": ["Drekkana"],
    "Courage": ["Drekkana"],
    "Efforts": ["Drekkana"],
    "Cooperation": ["Drekkana"],
    "Properties": ["Chaturthamsa"],
    "Home": ["Chaturthamsa"],
    "Material Comforts": ["Chaturthamsa", "Shodasamsa"],
    "Real Estate": ["Chaturthamsa"],
    "Progeny": ["Panchamsa", "Saptamsa"],
    "Creativity": ["Panchamsa"],
    "Children": ["Panchamsa", "Saptamsa"],
    "Diseases": ["Shasthamsa"],
    "Obstacles": ["Shasthamsa"],
    "Reproductive Potential": ["Saptamsa"],
    "Longevity": ["Ashtamsa"],
    "Death": ["Ashtamsa"],
    "Inheritance": ["Ashtamsa"],
    "Occult": ["Ashtamsa"],
    "Profession": ["Dasamsa"],
    "Status": ["Dasamsa"],
    "Public Life": ["Dasamsa"],
    "Misfortunes": ["Rudramsa", "Trimsamsa"],
    "Troubles": ["Rudramsa"],
    "Adversities": ["Rudramsa"],
    "Parents": ["Dwadasamsa"],
    "Heritage": ["Dwadasamsa"],
    "Past Karma": ["Dwadasamsa", "Shashtyamsa"],
    "Vehicles": ["Shodasamsa"],
    "Luxuries": ["Shodasamsa"],
    "Spiritual Pursuits": ["Vimsamsa"],
    "Religious Practices": ["Vimsamsa"],
    "Meditation": ["Vimsamsa"],
    "Learning": ["Siddhamsa"],
    "Knowledge": ["Siddhamsa"],
    "Strength": ["Nakshatramsa"],
    "Weaknesses": ["Nakshatramsa"],
    "Fortitude": ["Nakshatramsa"],
    "Evils": ["Trimsamsa"],
    "Malefic Influences": ["Trimsamsa"],
    "Skills": ["Khavedamsa"],
    "Talents": ["Khavedamsa"],
    "Capabilities": ["Khavedamsa"],
    "Past Life Karma": ["Shashtyamsa"],
    "Influence on Current Life": ["Shashtyamsa"]
}

# Example of accessing charts for a specific domain:
print(astrology_domains_charts["Wealth"])
print(astrology_domains_charts["Career"])


